[package]
name = "backup"
version = "0.3.0"
authors = ["shirokuro <46kuro212@gmail.com>"]
edition = "2018"

[dependencies]
tar = "0.4"
toml = "0.5"
walkdir = "2"
serde = "1"
serde_derive = "1"
chrono = "0.4"