[package]
name = "backup"
version = "0.1.0"
authors = ["shirokuro <46kuro212@gmail.com>"]
edition = "2018"

[dependencies]
tar = "0.4"
toml = "0.4"
chrono = "0.4"
log = "0.4"
env_logger = "0.6"
serde = "1.0"
serde_derive = "1.0"